# Generated by Django 3.0.3 on 2020-07-01 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('kernel_x', models.IntegerField()),
                ('kernel_y', models.IntegerField()),
            ],
        ),
    ]
