# Generated by Django 3.0.3 on 2020-07-02 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segment_tool', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='processed_image',
            field=models.ImageField(blank=True, upload_to='processed_images/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='kernel_x',
            field=models.IntegerField(default=48),
        ),
        migrations.AlterField(
            model_name='image',
            name='kernel_y',
            field=models.IntegerField(default=48),
        ),
    ]
